### ISSUE TITLE
Local Updates vs API Updates

### ISSUE THREAD

**Issue by noursaidi** [google/testrun#100]
If a device in `local/devices` is deleted whilst testrun is running, this remains in the testrun session. Consequently a subsequent API call to recreate the deleted device results in an error:

```
Traceback (most recent call last):
  File "/usr/local/google/home/elsaidi/test-run/venv/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/google/home/elsaidi/test-run/venv/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/google/home/elsaidi/test-run/venv/lib/python3.11/site-packages/fastapi/applications.py", line 290, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/google/home/elsaidi/test-run/venv/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/google/home/elsaidi/test-run/venv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/google/home/elsaidi/test-run/venv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/google/home/elsaidi/test-run/venv/lib/python3.11/site-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/google/home/elsaidi/test-run/venv/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/google/home/elsaidi/test-run/venv/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/google/home/elsaidi/test-run/venv/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/usr/local/google/home/elsaidi/test-run/venv/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/google/home/elsaidi/test-run/venv/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/google/home/elsaidi/test-run/venv/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/google/home/elsaidi/test-run/venv/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/google/home/elsaidi/test-run/venv/lib/python3.11/site-packages/fastapi/routing.py", line 241, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/google/home/elsaidi/test-run/venv/lib/python3.11/site-packages/fastapi/routing.py", line 167, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/google/home/elsaidi/test-run/framework/python/src/api/api.py", line 206, in save_device
    self._test_run.save_device(device, device_json)
  File "/usr/local/google/home/elsaidi/test-run/framework/python/src/core/testrun.py", line 250, in save_device
    with open(config_file_path, 'w+', encoding='utf-8') as config_file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/google/home/elsaidi/test-run/local/devices/aa O3-DIN-CPU/device_config.json'

```

**Comment by jboddey** [comment]
This is low priority at the moment as this would only be caused if the user was to manually delete/modify files whilst Testrun is running. Moving this to v1.2
