### ISSUE TITLE
Error - Container with that name exists

### ISSUE THREAD

**Issue by noursaidi** [google/testrun#90]
Received the following error. Launching testrun again does not resolve the issue unless there was some delay (5 minutes?) or to use `docker rm tr-ct-faux-dev`

```
Aug 07 12:24:04 validator INFO    Loaded the following validators: faux-dev 
Aug 07 12:24:04 validator DEBUG   Building network validators...
Aug 07 12:24:04 validator DEBUG   Building network validator faux-dev
Aug 07 12:24:06 validator DEBUG   Validator device built: faux-dev
Aug 07 12:24:06 validator DEBUG   Starting network devices
Aug 07 12:24:06 validator INFO    Starting device faux-dev
Aug 07 12:24:06 validator DEBUG   Image name: test-run/faux-dev
Aug 07 12:24:06 validator DEBUG   Container name: tr-ct-faux-dev
Aug 07 12:24:06 validator DEBUG   Network validator host user: elsaidi
Traceback (most recent call last):
  File "/usr/local/google/home/elsaidi/test-run/venv/lib/python3.11/site-packages/docker/api/client.py", line 268, in _raise_for_status
    response.raise_for_status()
  File "/usr/local/google/home/elsaidi/test-run/venv/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: http+docker://localhost/v1.41/containers/create?name=tr-ct-faux-dev

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/google/home/elsaidi/test-run/framework/python/src/core/test_runner.py", line 99, in <module>
    runner = TestRunner(config_file=args.config_file,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/google/home/elsaidi/test-run/framework/python/src/core/test_runner.py", line 42, in __init__
    self.test_run = TestRun(config_file=config_file,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/google/home/elsaidi/test-run/framework/python/src/core/testrun.py", line 109, in __init__
    self.start()
  File "/usr/local/google/home/elsaidi/test-run/framework/python/src/core/testrun.py", line 164, in start
    self._start_network()
  File "/usr/local/google/home/elsaidi/test-run/framework/python/src/core/testrun.py", line 251, in _start_network
    if not self.get_net_orc().start():
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/google/home/elsaidi/test-run/framework/python/src/net_orc/network_orchestrator.py", line 87, in start
    self.start_network()
  File "/usr/local/google/home/elsaidi/test-run/framework/python/src/net_orc/network_orchestrator.py", line 130, in start_network
    self.validator.start()
  File "/usr/local/google/home/elsaidi/test-run/framework/python/src/net_orc/network_validator.py", line 60, in start
    self._start_network_devices()
  File "/usr/local/google/home/elsaidi/test-run/framework/python/src/net_orc/network_validator.py", line 141, in _start_network_devices
    self._start_network_device(net_device)
  File "/usr/local/google/home/elsaidi/test-run/framework/python/src/net_orc/network_validator.py", line 150, in _start_network_device
    device.container = client.containers.run(
                       ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/google/home/elsaidi/test-run/venv/lib/python3.11/site-packages/docker/models/containers.py", line 858, in run
    container = self.create(image=image, command=command,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/google/home/elsaidi/test-run/venv/lib/python3.11/site-packages/docker/models/containers.py", line 917, in create
    resp = self.client.api.create_container(**create_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/google/home/elsaidi/test-run/venv/lib/python3.11/site-packages/docker/api/container.py", line 431, in create_container
    return self.create_container_from_config(config, name, platform)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/google/home/elsaidi/test-run/venv/lib/python3.11/site-packages/docker/api/container.py", line 448, in create_container_from_config
    return self._result(res, True)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/google/home/elsaidi/test-run/venv/lib/python3.11/site-packages/docker/api/client.py", line 274, in _result
    self._raise_for_status(response)
  File "/usr/local/google/home/elsaidi/test-run/venv/lib/python3.11/site-packages/docker/api/client.py", line 270, in _raise_for_status
    raise create_api_error_from_http_exception(e) from e
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/google/home/elsaidi/test-run/venv/lib/python3.11/site-packages/docker/errors.py", line 39, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation) from e
docker.errors.APIError: 409 Client Error for http+docker://localhost/v1.41/containers/create?name=tr-ct-faux-dev: Conflict ("Conflict. The container name "/tr-ct-faux-dev" is already in use by container "3c7410d3402ccb1b307db64eb57ab59dbef922a9d79d0762f677f487f59becff". You have to remove (or rename) that container to be able to reuse that name.")
Aug 07 12:24:00 net_orc  DEBUG   Discovered device 4e:c5:b3:c2:70:41. Waiting for device to obtain IP
Aug 07 12:24:00 net_orc  DEBUG   Device with MAC address 4e:c5:b3:c2:70:41 does not exist in device repository
```

**Comment by jboddey** [comment]
Closing this issue as this has not been seen for a while - may have been fixed.
